
<?php
function bookmodal_block_info() {
  $blocks['modal_test'] = array(
    'info' => t( 'Modal Test Block' ),
  );

  return $blocks;
}
?>
<?php

function bookmodal_block_view( $block_name ) {
  if ( $block_name == 'modal_test' ) {

    ctools_include( 'modal' );
    ctools_include( 'ajax' );
    ctools_modal_add_js();

    return array(
      'subject' => t( 'Modal Test Block!' ),
      'content' => ctools_modal_text_button( t( 'Click Here!' ), 'modal-test-callback/nojs', t( 'Click Here!' ) ),
    );
  }
}
?>
<?php
function bookmodal_menu() {
  $items['modal-test-callback/%ctools_js'] = array(
    'page callback' => 'mymodule_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('create article content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}
?>

<?php

function bookmodal_modal_callback($js = false) {
  // If the user doesn't have javascript, redirect them to the normal node/add/article page
  if (!$js) {
    drupal_goto('node/add/article');
  }
  else {
    // Javascript is on, prepare ctools modals.
    ctools_include('ajax');
    ctools_include('modal');
    // Pull in the global user, and prepare a blank node to pass to the node
    global $user;
    $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'article', 'language' => LANGUAGE_NONE);
    $node->title = NULL;
    node_object_prepare($node);
 // Add the node.pages.inc so that functions from the form can be used.
    module_load_include('inc', 'node', 'node.pages');

    // Prepare the form state, ctools reqruies ajax / title.  The node add form
    // requires node.
    $form_state = array(
      'ajax' => true,
      'title' => t('Add a new Article'),
      'node' => $node,
    );

    // Do the ctools_modal_form_wrapping of the node form.  Returns a set of
    // ajax commands in output.
    $output = ctools_modal_form_wrapper('article_node_form', $form_state);

    if (!empty($form_state['executed'])) {

      // Add the responder javascript, required by ctools
      ctools_add_js('ajax-responder');

      // Create ajax command array, dismiss the modal window.
      $output = array();
      $output[] = ctools_modal_command_dismiss();
    }

    print ajax_render($output);
    exit;
  }
}
?>
